        # 3. Record a demo artifact to show the real flow works
        artifact = self.artifact_registry.create_code_artifact(
            path=f"/output/{agent_id}/{task_id}.py",
            content=f"# Generated by {agent_id} for task {task_id}\n# Model: {profile.model}",
            agent_id=agent_id,
            task_id=task_id,
            execution_id=self.execution_id,
        )

        result["artifact"] = {
            "artifact_id": artifact.artifact_id,
            "hash": artifact.content_hash,
            "path": artifact.path,
        }

        return result

    def stats(self) -> Dict[str, Any]:
        """Get full runtime statistics."""
        return {
            "execution_id": self.execution_id,
            "agents": {
                aid: {
                    "domain": p.domain,
                    "model": p.model,
                    "active": p.active_tasks,
                    "completed": p.total_tasks_completed,
                    "failed": p.total_tasks_failed,
                    "load": p.load_factor,
                }
                for aid, p in self.profiles.items()
            },
            "tool_telemetry": self.tool_router.get_telemetry(50),
            "artifacts": self.artifact_registry.stats(),
            "scheduler": self.scheduler.stats(),
        }


# ═══════════════════════════════════════════════════
# Singleton
# ═══════════════════════════════════════════════════

_runtime: Optional[LiveAgentRuntime] = None

def get_runtime() -> LiveAgentRuntime:
    """Get or create the singleton live agent runtime."""
    global _runtime
    if _runtime is None:
        _runtime = LiveAgentRuntime()
    return _runtime