#!/usr/bin/env python3
"""cognitive_mcp_daemon.py — Unified MCP Governance + Cognitive Capability Fabric daemon."""
import json, logging, os, sys, time
sys.path.insert(0, "/services/runtime/events")
sys.path.insert(0, "/services/runtime/mcp")
sys.path.insert(0, "/services/runtime/capabilities")
sys.path.insert(0, "/services/runtime/cognitive_capabilities")
sys.path.insert(0, "/services/runtime/reasoning")
sys.path.insert(0, "/services/runtime/planner_runtime")
sys.path.insert(0, "/services/runtime/state")
sys.path.insert(0, "/brain/streaming")
sys.path.insert(0, "/services/runtime/pr_runtime")
from event_bus import get_bus, publish
bus = get_bus()
log = logging.getLogger("cognitive-mcp")
logging.basicConfig(level=logging.INFO, format="%(asctime)s [cognitive-mcp] %(name)s: %(levelname)s: %(message)s")
log.info("=== COGNITIVE MCP DAEMON STARTING ===")
from planner_events import start as s1; s1()
from delivery_events import start as s2; s2()
from recovery_events import start as s3; s3()
from governance_events import start as s4; s4()
from drift_events import start as s5; s5()
from organizational_events import start as s6; s6()
from planner_daemon import start_daemon; start_daemon()
from taskgraph_runtime import start_graph; start_graph()
from runtime_state_watcher import start_watcher; start_watcher()
from priority_runtime import start_priority; start_priority()
from planner_memory_sync import start_memory; start_memory()
from execution_dispatcher import start_dispatcher; start_dispatcher()
from organizational_state_graph import start_graph as sg; sg()
from workflow_state_engine import start_engine as sw; sw()
from capability_state_mapper import start_mapper; start_mapper()
from live_runtime_topology import start_topo; start_topo()
from live_embedding_pipeline import start_pipe; start_pipe()
from incremental_memory_sync import start_sync; start_sync()
from event_embedding_router import start_router; start_router()
from pr_autogenerator import start_gen; start_gen()
from mcp_tool_registry import REG; REG.register_all()
from mcp_github_integration import GITHUB; GITHUB.register()
from mcp_brain_integration import BRAIN; BRAIN.register()
from mcp_infrastructure_integration import INFRA; INFRA.register()
from mcp_security_integration import SEC; SEC.register()
from mcp_runtime_bridge import BRIDGE; BRIDGE.register_capabilities()
from mcp_capability_router import start_router as srr; srr()
from mcp_security_governor import start_gov as g1; g1()
from mcp_event_bridge import start_bridge; start_bridge()
from mcp_audit_engine import start_audit; start_audit()
from mcp_recovery_adapter import start_adapter; start_adapter()
from mcp_context_router import start_ctx; start_ctx()
from mcp_oracle_sync import start_oracle; start_oracle()
from mcp_governance_engine import start_gov as g2; g2()
from mcp_agent_permissions import start_perms; start_perms()
from mcp_workflow_adapter import start_wf; start_wf()
from capability_learning_engine import start_learn; start_learn()
from capability_escalation_engine import start as ce; ce()
from capability_trust_engine import start as ct; ct()
from capability_memory_mapper import start as cm; cm()
from capability_learning_runtime import start as cl; cl()
from capability_usage_analytics import start as cu; cu()
from capability_recovery_engine import start as cr; cr()
from capability_conflict_resolver import start as cc; cc()
from capability_evolution_engine import start as cg; cg()
from organizational_reasoning_engine import start as ore; ore()
from workflow_reasoning_engine import start as wre; wre()
from capability_reasoner import start as car; car()
from strategic_reasoning_engine import start as sre; sre()
from escalation_reasoner import start as ere; ere()
from governance_reasoner import start as gre; gre()
from recovery_reasoner import start as rre; rre()
from optimization_reasoner import start as ore2; ore2()
log.info("=== COGNITIVE MCP DAEMON FULLY OPERATIONAL ===")
publish("runtime.start", {"status":"operational","layers":9},"cognitive-mcp")
from mcp_gateway import get_gateway
from organizational_reasoning_engine import ENG
gw = get_gateway()
gw.register_capability("cognitive.reason", lambda call_id, agent, situation, **kw: ENG.reason(situation), {"domain":"cognitive","governance":"low"})
while True:
    time.sleep(30)
    publish("runtime.health", {"layer":"cognitive","status":"ok"},"cognitive-mcp")
