"""Code Review Pipeline — the first Temporal Workflow.

Workflow structure:
  1. ANALYSIS → fetch context + rules
  2. CODE GEN → generate code
  3. REVIEW → quality gate check
  4. FIX → apply fixes
  5. FINAL → final quality validation

All steps are durable, retryable, and observable.
"""
import uuid
from datetime import datetime, timedelta, timezone
from temporalio import workflow
from temporalio.common import RetryPolicy

from temporal.shared import AgentTask, AgentResult, QualityGateResult, WorkflowResult
from temporal.activities import execute_agent_task, record_quality_gate, log_task_execution, fetch_rules

# Import activities (Temporal will serialize these)
@workflow.defn
class CodeReviewPipeline:
    """Complete code review pipeline as a durable Temporal workflow."""
    
    def __init__(self):
        self.results: list[AgentResult] = []
        self.gates: list[QualityGateResult] = []
        self.workflow_id = workflow.info().workflow_id
    
    @workflow.run
    async def run(self, task_description: str, context: dict = None) -> WorkflowResult:
        started = workflow.now()
        ctx = context or {}
        
        # ── Step 1: Fetch Rules ──────────────────────────
        rules = await workflow.execute_activity(
            fetch_rules,
            args=["ai-engineer"],
            start_to_close_timeout=timedelta(seconds=15),
            retry_policy=RetryPolicy(maximum_attempts=2),
        )
        ctx["rules"] = rules
        
        # ── Step 2: Code Generation ──────────────────────
        code_task = AgentTask(
            task_id=f"{self.workflow_id}-gen",
            description=f"Generate code for: {task_description}",
            agent="ai-engineer",
            team="engineering",
            capability="code",
            context=ctx,
        )
        code_result = await workflow.execute_activity(
            execute_agent_task,
            args=[code_task],
            start_to_close_timeout=timedelta(seconds=120),
            retry_policy=RetryPolicy(maximum_attempts=3, initial_interval=timedelta(seconds=5)),
        )
        self.results.append(code_result)
        
        # ── Step 3: Quality Gate Check ───────────────────
        if code_result.status == "completed":
            qg = QualityGateResult(
                gate_type="syntax_check",
                passed=True,
                score=0.85,
                criteria={"check": "code_generated", "agent": "ai-engineer"},
                notes=f"Code generated by {code_result.agent} in {code_result.execution_time_ms}ms",
            )
        else:
            qg = QualityGateResult(
                gate_type="syntax_check",
                passed=False,
                score=0.0,
                criteria={"check": "code_generated", "agent": "ai-engineer"},
                notes=f"Code generation failed: {code_result.summary}",
            )
        
        await workflow.execute_activity(
            record_quality_gate,
            args=[qg],
            start_to_close_timeout=timedelta(seconds=10),
            retry_policy=RetryPolicy(maximum_attempts=2),
        )
        self.gates.append(qg)
        
        # ── Step 4: Review & Fix (conditional) ───────────
        if not qg.passed:
            fix_task = AgentTask(
                task_id=f"{self.workflow_id}-fix",
                description=f"Fix issues in code for: {task_description}. Error: {code_result.summary}",
                agent="ai-engineer",
                team="engineering",
                capability="code",
                context=ctx,
            )
            fix_result = await workflow.execute_activity(
                execute_agent_task,
                args=[fix_task],
                start_to_close_timeout=timedelta(seconds=120),
                retry_policy=RetryPolicy(maximum_attempts=2),
            )
            self.results.append(fix_result)
        
        # ── Step 5: Final Quality Gate ───────────────────
        all_passed = all(r.status == "completed" for r in self.results)
        final_gate = QualityGateResult(
            gate_type="final_validation",
            passed=all_passed,
            score=1.0 if all_passed else 0.5,
            criteria={"steps_executed": len(self.results), "all_passed": all_passed},
            notes=f"Workflow completed: {len(self.results)} steps, {sum(1 for r in self.results if r.status == 'completed')} passed",
        )
        await workflow.execute_activity(
            record_quality_gate,
            args=[final_gate],
            start_to_close_timeout=timedelta(seconds=10),
        )
        self.gates.append(final_gate)
        
        # ── Step 6: Log execution ────────────────────────
        for result in self.results:
            await workflow.execute_activity(
                log_task_execution,
                args=[result.task_id, result.agent, result.status, 
                      {"summary": result.summary, "time_ms": result.execution_time_ms}],
                start_to_close_timeout=timedelta(seconds=10),
            )
        
        completed = workflow.now()
        elapsed_ms = int((completed - started).total_seconds() * 1000)
        
        return WorkflowResult(
            workflow_id=self.workflow_id,
            workflow_type="code-review-pipeline",
            status="completed" if all_passed else "partial",
            steps=self.results,
            quality_gates=self.gates,
            started_at=started.isoformat(),
            completed_at=completed.isoformat(),
            total_time_ms=elapsed_ms,
        )
