#!/usr/bin/env python3
"""pr_autogenerator.py -- Generates GitHub PRs autonomously from issue/plan events."""
import json, logging, os, requests, subprocess, sys, threading, time
from datetime import datetime, timezone
from event_bus import get_bus, publish
log = logging.getLogger("pr-gen")

TOKEN = os.environ.get("DS_GITHUB_9569466F__TOKEN", "")
REPO = "nexifyai-dev/nexifyai-website-sicherheitskopie"
API = "https://api.github.com"
HDRS = {"Authorization": f"Bearer {TOKEN}", "Accept": "application/vnd.github.v3+json"} if TOKEN else {}

class PRAutogenerator:
    def __init__(self):
        self.bus = get_bus()
    def start(self):
        self.bus.subscribe("planner.task", self._on_task, "pr:task")
        log.info("PR autogenerator active")
    def _on_task(self, event):
        payload = event.get("payload",{})
        task_type = payload.get("type","")
        if task_type in ("deliver","deploy","release"):
            self._create_pr(f"auto: {payload.get('reason','automated change')}")
    def _create_pr(self, title):
        if not TOKEN: return {"ok":False,"error":"no_token"}
        try:
            r = requests.post(f"{API}/repos/{REPO}/pulls", headers=HDRS,
                json={"title":title,"head":"auto-change","base":"main","body":f"## Autonomous PR\n\n**Generated:** {datetime.now(timezone.utc).isoformat()}\n**Source:** PR Runtime\n\nAutomated change generated by enterprise runtime."}, timeout=10)
            if r.status_code == 201:
                d = r.json(); publish("delivery.pr_created", {"pr_num":d["number"],"url":d["html_url"],"title":title},"pr-runtime")
                return {"ok":True,"num":d["number"],"url":d["html_url"]}
            return {"ok":False,"code":r.status_code}
        except Exception as e: return {"ok":False,"error":str(e)[:50]}

GEN = None
def start_gen():
    global GEN
    if GEN is None: GEN = PRAutogenerator(); GEN.start()
    return GEN

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO); start_gen(); print("PR autogenerator running")
