#!/usr/bin/env python3
"""event_bus_daemon.py -- Starts event bus + all event drivers. Persistent organizational runtime."""
import json, logging, os, sys, time
sys.path.insert(0, "/services/runtime/events")
sys.path.insert(0, "/services/runtime/planner_runtime")
sys.path.insert(0, "/services/runtime/state")
sys.path.insert(0, "/brain/streaming")
sys.path.insert(0, "/services/runtime/pr_runtime")
from event_bus import get_bus, publish
bus = get_bus()
log = logging.getLogger("event-daemon")
logging.basicConfig(level=logging.INFO, format="%(asctime)s [eventd] %(name)s: %(levelname)s: %(message)s")
log.info("=== EVENT BUS DAEMON STARTING ===")
from planner_events import start as s1; s1()
from delivery_events import start as s2; s2()
from recovery_events import start as s3; s3()
from governance_events import start as s4; s4()
from drift_events import start as s5; s5()
from organizational_events import start as s6; s6()
from planner_daemon import start_daemon; start_daemon()
from taskgraph_runtime import start_graph; start_graph()
from runtime_state_watcher import start_watcher; start_watcher()
from priority_runtime import start_priority; start_priority()
from planner_memory_sync import start_memory; start_memory()
from execution_dispatcher import start_dispatcher; start_dispatcher()
from organizational_state_graph import start_graph as sg; sg()
from workflow_state_engine import start_engine as sw; sw()
from capability_state_mapper import start_mapper; start_mapper()
from live_runtime_topology import start_topo; start_topo()
from live_embedding_pipeline import start_pipe; start_pipe()
from incremental_memory_sync import start_sync; start_sync()
from event_embedding_router import start_router; start_router()
from pr_autogenerator import start_gen; start_gen()
log.info("=== EVENT BUS DAEMON FULLY OPERATIONAL ===")
publish("runtime.start", {"status":"operational","modules":"full"},"event-daemon")
while True:
    time.sleep(30)
    publish("runtime.health",{"status":"ok"},"event-daemon")
